=== Lranger321/XML/лабы/flower.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT flowerList (flower*)>
        <!ELEMENT flower (id,name,
                class,
                avg_height,
                flowered,
                extra_info)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT class (#PCDATA)>
        <!ELEMENT avg_height (#PCDATA)>
        <!ELEMENT flowered (#PCDATA)>
        <!ELEMENT extra_info (#PCDATA)>

=== Lranger321/XML/лабы/flowers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE flowerList SYSTEM "flower.dtd">
<flowerList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="FLOWER">
    <flower>
        <id>1</id>
        <name>Роза</name>
        <class>Розовые</class>
        <avg_height>60</avg_height>
        <flowered>true</flowered>
        <extra_info>Основные или маточные, ветви и ветви с законченным ростом и пять типов однолетних побегов</extra_info>
    </flower>
    <flower>
        <id>2</id>
        <name>Земляника</name>
        <class>Розовые</class>
        <avg_height>13</avg_height>
        <flowered>true</flowered>
        <extra_info>Листья тройчатые, сложной формы, на длинных, достигающих высоты в 10 см стебельках</extra_info>
    </flower>
    <flower>
        <id>3</id>
        <name>Шиповник</name>
        <class>Розовые</class>
        <avg_height>20</avg_height>
        <flowered>true</flowered>
        <extra_info>Розой в ботанической литературе часто называют и сам шиповник</extra_info>
    </flower>
    <flower>
        <id>4</id>
        <name>Фиалка</name>
        <class>Фиалковые</class>
        <avg_height>8</avg_height>
        <flowered>true</flowered>
        <extra_info>Пурпурный оттенок, и фиолетовыми цветками</extra_info>
    </flower>
    <flower>
        <id>5</id>
        <name>Гигантская лилия</name>
        <class>Лилейные</class>
        <avg_height>300</avg_height>
        <flowered>true</flowered>
        <extra_info>Луковицы её бывают величиной почти с человеческую голову</extra_info>
    </flower>
</flowerList>
